### ISSUE TITLE
Pixel format conversion shaders

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/gde_gozen#20]
# Pixel conversion shaders
As mentioned in #19 we need the shaders for more efficiently converting NV12/YUV420P pixel formats to RGB, sws_scale won't cut it as performance is worse then the software decoding for NV12 and YUV420P could also benefit from using shaders.

## Possible problems
This does cause some issues though as using hardware frame decoding sends the frame to the GPU and needs to be send back to the CPU memory to then be send back to the GPU for the shader, not a too resource intensive task, but if we could find a way to keep the data in the GPU memory to directly send to the shader this would be ideal as it would save some amount of traffic. This is most likely not going to be possible or out of my skill level.

Another problem is that I'm talking about NV12, but there is no guarantee that the pixel format would be NV12, so when creating a shader, we need to take that in mind to support multiple pixel formats which could become an issue and another performance bottleneck.

There probably are some other problems here, I had an attempt at this with compute shaders, but those can't be used in Compatibility mode and some users had issues getting it to work with certain video files even though the pixel format was correct.

## Tasks
- [x] Check if video file is using YUV420P or NV12, block others for now;
- [x] Find way to pass array to shader (pass Y to shader and render brightness);
- [x] Create Red image with Y data;
- [x] Create YUV420P shader;
- [x] Create NV12 shader;
- [x] ~~If normal shaders don't work, switch to compute shaders;~~

**Comment by voylin** [comment]
This is working!
