### ISSUE TITLE
Renderer update

### ISSUE THREAD

**Issue by voylin** [VoylinsGamedevJourney/gde_gozen#31]
## TODO

- [x] Get dictionary for video codecs;
- [x] Get dictionary for audio codecs;
- [x] Make certain that all variables are set when open();
- [x] Render video frames;
- [x] Render audio data;
- [x] Get H264 render profiles and create a setter;
